// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFFJy-EXnWjhHaFCEaxNqonKhUCqpj1CU',
    appId: '1:816457567870:web:5dca5c6e3baa2d2c08522f',
    messagingSenderId: '816457567870',
    projectId: 'auction-demo-e1405',
    authDomain: 'auction-demo-e1405.firebaseapp.com',
    storageBucket: 'auction-demo-e1405.appspot.com',
    measurementId: 'G-G9CYZNCD53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHSHDmp6oH-wMjpm2nClKVrEeOKfvlItY',
    appId: '1:816457567870:android:3d6fafac4b43096308522f',
    messagingSenderId: '816457567870',
    projectId: 'auction-demo-e1405',
    storageBucket: 'auction-demo-e1405.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXfwtPkw2H6G3BqHh6cEMJU3dX_DjtwRA',
    appId: '1:816457567870:ios:e1bbbfaa65b66aba08522f',
    messagingSenderId: '816457567870',
    projectId: 'auction-demo-e1405',
    storageBucket: 'auction-demo-e1405.appspot.com',
    androidClientId: '816457567870-fl5k77iqkog1qths3pq8ec38vo1a7ur7.apps.googleusercontent.com',
    iosClientId: '816457567870-jvmongpc3h7bk8p1pq46s03te76bhg0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.auctiondemo',
  );
}
